### PR TITLE
refactor: use same prefix for plugin functions

### PR DESCRIPTION
**Pull request by mcnaveen**
This PR refactors the code to use the same prefix all over the plugin

P.S: The plugin is still on v1.0.0 let me know if you want to bump it to the next patch version.

### CODE REVIEW

**Review by ShubhamPalriwala — COMMENTED** [review]
Hey, thanks for the PR! This looks good, however, I can see some other methods as well in 
- https://github.com/formbricks/wordpress/blob/main/admin/class-formbricks-admin.php
- And in files inside directory: https://github.com/formbricks/wordpress/blob/main/includes
- https://github.com/formbricks/wordpress/blob/main/public/class-formbricks-public.php

Can you please take a look at the above files as well (possibly remove the ones that arent needed and handle the required ones)?

Thanks a lot 💪🏼

**Comment by mcnaveen** [comment]
Hi, @ShubhamPalriwala You can safely ignore these Class names. This won't be an issue.

**Comment by ShubhamPalriwala** [comment]
Can we remove these if they are not required?

**Comment by mcnaveen** [comment]
Nope, it's needed for the plugin functionality. But it doesn't violate or conflict with other plugins in the installation. So better to keep it as it is.

**Comment by ShubhamPalriwala** [comment]
Ahh okay! Id still prefer to rename them as well in line with our other methods ie with the _formbricks__ prefix. 

PS: This will make us more confident of our next review application!

**Comment by mcnaveen** [comment]
@ShubhamPalriwala Every other plugin in the WordPress repository follow this. It's better to keep the name of the Class this way.

**Pull request merged**
